name: image-segmentation-keras
channels:
- defaults
dependencies:
- h5py>=2.7,<3
- hdf5>=1.8,<2
- Keras=2.1.6
- matplotlib=3.0
- numpy=1
- pip>=9.0.1,<=18.1
- python=3.6.*
- scipy=1
- theano=1
- pip:
  - black==18.9b0
  - opencv-python==3.4.1.15
  - tensorflow-gpu>=1.8.0,<=1.9.0
  - tqdm==4.28.1
